// AUTO-GENERATED by scripts/sync-artworks.mjs — do not edit by hand.
// Regenerate: npm run sync-artworks
//
// ADD an image:
//   1. Drop a .jpg/.png into public/images/{paintings|drawings|portraits}/{subcategory}/
//      Example: public/images/paintings/recent/evening-light.jpg
//   2. (Optional) Add evening-light.json alongside it:
//      { "title": "Evening Light", "size": "60 × 80 cm", "year": 2024, "available": false }
//   3. Run npm run sync-artworks (or restart dev — runs automatically)
//
// REMOVE an image: delete the image file (+ .json if any), then sync again.
//
// Subcategories:
//   paintings: recent | naar-model | still-life-landscape | featured
//   drawings:  naar-model | still-life-interior
//   portraits: drawings | paintings

export type ArtworkCategory = "paintings" | "drawings" | "portraits";

export type Artwork = {
  id: string;
  src: string;
  title: string;
  size: string | null;
  year: number | null;
  category: ArtworkCategory;
  subcategory: string;
  available: boolean;
};

export const artworks: Artwork[] = [
  {
    "id": "drawings-naar-model-003735dd-32e4-4ab1-bc2d-4ff70af75bf6",
    "src": "/images/drawings/drawings-naar-model-003735dd-32e4-4ab1-bc2d-4ff70af75bf6.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-01598edb-752d-408c-83b9-60d47d5212e9",
    "src": "/images/drawings/drawings-naar-model-01598edb-752d-408c-83b9-60d47d5212e9.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-033dfed6-719c-4f03-ad36-10752339e1c0",
    "src": "/images/drawings/drawings-naar-model-033dfed6-719c-4f03-ad36-10752339e1c0.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-08cd69dd-560b-462b-9bdf-5f7869ecaa30",
    "src": "/images/drawings/drawings-naar-model-08cd69dd-560b-462b-9bdf-5f7869ecaa30.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-0bd997da-2524-4de9-a34f-fe9c04a1f680",
    "src": "/images/drawings/drawings-naar-model-0bd997da-2524-4de9-a34f-fe9c04a1f680.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-0c4f6fb5-e43c-45bc-8576-6d9868d76a0a",
    "src": "/images/drawings/drawings-naar-model-0c4f6fb5-e43c-45bc-8576-6d9868d76a0a.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-0f6ce76a-4892-4b4b-9df2-34c09d9836de",
    "src": "/images/drawings/drawings-naar-model-0f6ce76a-4892-4b4b-9df2-34c09d9836de.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-174537da-9a7a-4a9f-9d99-eed99d6f489d",
    "src": "/images/drawings/drawings-naar-model-174537da-9a7a-4a9f-9d99-eed99d6f489d.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-18c91b79-8dde-4329-b43e-e20b6e50b602",
    "src": "/images/drawings/drawings-naar-model-18c91b79-8dde-4329-b43e-e20b6e50b602.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-19210d32-1c7f-44b1-81e5-717cbdcb77d4",
    "src": "/images/drawings/drawings-naar-model-19210d32-1c7f-44b1-81e5-717cbdcb77d4.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-1afee176-87ae-455c-96a3-1b7186855e3c",
    "src": "/images/drawings/drawings-naar-model-1afee176-87ae-455c-96a3-1b7186855e3c.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-1b8916b0-3a3a-4bda-9c61-9e0233506dbc",
    "src": "/images/drawings/drawings-naar-model-1b8916b0-3a3a-4bda-9c61-9e0233506dbc.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-1ee48f22-34a0-4a22-802a-e175962bf44e",
    "src": "/images/drawings/drawings-naar-model-1ee48f22-34a0-4a22-802a-e175962bf44e.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-1fd81bf3-9a64-4a8d-b569-aecfce3cdd17",
    "src": "/images/drawings/drawings-naar-model-1fd81bf3-9a64-4a8d-b569-aecfce3cdd17.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-222765d9-7599-408f-84fc-122da6a43739",
    "src": "/images/drawings/drawings-naar-model-222765d9-7599-408f-84fc-122da6a43739.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-22cca20d-0297-44eb-bf35-08675557817c",
    "src": "/images/drawings/drawings-naar-model-22cca20d-0297-44eb-bf35-08675557817c.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2449bfc4-7fbe-4265-bf5f-15a8b8782923",
    "src": "/images/drawings/drawings-naar-model-2449bfc4-7fbe-4265-bf5f-15a8b8782923.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2a637e37-684f-435a-9e87-9c0d386152cd",
    "src": "/images/drawings/drawings-naar-model-2a637e37-684f-435a-9e87-9c0d386152cd.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2aff322a-9206-4864-bd96-5fd362432f33",
    "src": "/images/drawings/drawings-naar-model-2aff322a-9206-4864-bd96-5fd362432f33.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2b000668-8100-480f-9f72-ac480c08379f",
    "src": "/images/drawings/drawings-naar-model-2b000668-8100-480f-9f72-ac480c08379f.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2cca3cbc-1c22-4352-a325-fe80ee067037",
    "src": "/images/drawings/drawings-naar-model-2cca3cbc-1c22-4352-a325-fe80ee067037.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2d88ad0c-7d29-4524-8ad2-aeffa838c674",
    "src": "/images/drawings/drawings-naar-model-2d88ad0c-7d29-4524-8ad2-aeffa838c674.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2dda0c74-49b1-47a8-b6c2-ccea19dce3e4",
    "src": "/images/drawings/drawings-naar-model-2dda0c74-49b1-47a8-b6c2-ccea19dce3e4.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2eacdc8d-de18-4f1f-85d1-38bbf0b1dba2",
    "src": "/images/drawings/drawings-naar-model-2eacdc8d-de18-4f1f-85d1-38bbf0b1dba2.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-2f87edec-4b8c-498b-b773-bad53d1e3110",
    "src": "/images/drawings/drawings-naar-model-2f87edec-4b8c-498b-b773-bad53d1e3110.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-32e160b9-d9cb-425f-9dad-3c2fab0d93bf",
    "src": "/images/drawings/drawings-naar-model-32e160b9-d9cb-425f-9dad-3c2fab0d93bf.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-34237dae-14a6-45ed-aed4-bda768e5a425",
    "src": "/images/drawings/drawings-naar-model-34237dae-14a6-45ed-aed4-bda768e5a425.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-3a18f15e-1670-449d-a9e9-946d8f057f71",
    "src": "/images/drawings/drawings-naar-model-3a18f15e-1670-449d-a9e9-946d8f057f71.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-3c706967-f2cd-407e-bba3-c9a30ef25844",
    "src": "/images/drawings/drawings-naar-model-3c706967-f2cd-407e-bba3-c9a30ef25844.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-3cabab03-9b6d-4d87-aafa-534dffdaadab",
    "src": "/images/drawings/drawings-naar-model-3cabab03-9b6d-4d87-aafa-534dffdaadab.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-3e21bcfc-af80-4b04-afca-e82e1909f388",
    "src": "/images/drawings/drawings-naar-model-3e21bcfc-af80-4b04-afca-e82e1909f388.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-406713d2-d0c5-4ce5-9a2d-cdde43092966",
    "src": "/images/drawings/drawings-naar-model-406713d2-d0c5-4ce5-9a2d-cdde43092966.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-4842c546-fc3d-4e69-9ea2-b3e01f3403e8",
    "src": "/images/drawings/drawings-naar-model-4842c546-fc3d-4e69-9ea2-b3e01f3403e8.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-4f0eb379-75d8-4df6-a6d8-93e0cf525fef",
    "src": "/images/drawings/drawings-naar-model-4f0eb379-75d8-4df6-a6d8-93e0cf525fef.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-4f5627fd-0f55-4902-a3fc-4dafd84a6180",
    "src": "/images/drawings/drawings-naar-model-4f5627fd-0f55-4902-a3fc-4dafd84a6180.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-51031b1e-a3ab-46ac-b6e3-0d3a8391d5f6",
    "src": "/images/drawings/drawings-naar-model-51031b1e-a3ab-46ac-b6e3-0d3a8391d5f6.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-51878ec6-a96d-434a-95f3-454969d3e0d1",
    "src": "/images/drawings/drawings-naar-model-51878ec6-a96d-434a-95f3-454969d3e0d1.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-53e02959-d3a4-467f-b4dd-67b9e39817d0",
    "src": "/images/drawings/drawings-naar-model-53e02959-d3a4-467f-b4dd-67b9e39817d0.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-5459bfbe-1386-42fd-b37b-b4a4b0e887b5",
    "src": "/images/drawings/drawings-naar-model-5459bfbe-1386-42fd-b37b-b4a4b0e887b5.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-57a30437-cd56-42eb-9ab8-5dd92300bdf9",
    "src": "/images/drawings/drawings-naar-model-57a30437-cd56-42eb-9ab8-5dd92300bdf9.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-5d2e1ae8-b370-4499-9596-30e671af73db",
    "src": "/images/drawings/drawings-naar-model-5d2e1ae8-b370-4499-9596-30e671af73db.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-5e0476de-f12a-4c50-a07f-1d0ec343a36f",
    "src": "/images/drawings/drawings-naar-model-5e0476de-f12a-4c50-a07f-1d0ec343a36f.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-5f0b3551-2b94-40eb-a35f-752f483b708e",
    "src": "/images/drawings/drawings-naar-model-5f0b3551-2b94-40eb-a35f-752f483b708e.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-745fa77d-a496-4413-a292-3993c76c07a3",
    "src": "/images/drawings/drawings-naar-model-745fa77d-a496-4413-a292-3993c76c07a3.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-765d8bad-343b-454a-ba89-cbc99c978518",
    "src": "/images/drawings/drawings-naar-model-765d8bad-343b-454a-ba89-cbc99c978518.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-771860fe-78cd-486c-b180-2abfc31b35ee",
    "src": "/images/drawings/drawings-naar-model-771860fe-78cd-486c-b180-2abfc31b35ee.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-79a78f6b-f899-4663-9dc9-0568c7bbc604",
    "src": "/images/drawings/drawings-naar-model-79a78f6b-f899-4663-9dc9-0568c7bbc604.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-7f1b6171-539c-49c8-b8f2-8cac5df05f23",
    "src": "/images/drawings/drawings-naar-model-7f1b6171-539c-49c8-b8f2-8cac5df05f23.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-8175ba0c-2b9d-49a5-8525-9437dc058e98",
    "src": "/images/drawings/drawings-naar-model-8175ba0c-2b9d-49a5-8525-9437dc058e98.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-8373d5c1-b4b0-4480-b0e5-7e886f2da24d",
    "src": "/images/drawings/drawings-naar-model-8373d5c1-b4b0-4480-b0e5-7e886f2da24d.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-84116803-23e7-43b9-a455-1832bc336e8f",
    "src": "/images/drawings/drawings-naar-model-84116803-23e7-43b9-a455-1832bc336e8f.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-84adad6a-f35d-4586-b694-acbd86bd4634",
    "src": "/images/drawings/drawings-naar-model-84adad6a-f35d-4586-b694-acbd86bd4634.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-8614033d-4beb-4ccd-86a6-a52ed1462ee2",
    "src": "/images/drawings/drawings-naar-model-8614033d-4beb-4ccd-86a6-a52ed1462ee2.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-882478ca-cd02-4809-81a5-69e72e9222e9",
    "src": "/images/drawings/drawings-naar-model-882478ca-cd02-4809-81a5-69e72e9222e9.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-8ce36bff-61a1-486e-a8b8-94ff0aeb9f13",
    "src": "/images/drawings/drawings-naar-model-8ce36bff-61a1-486e-a8b8-94ff0aeb9f13.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-8e6f6e15-1357-45bd-89ab-a0edd985cfad",
    "src": "/images/drawings/drawings-naar-model-8e6f6e15-1357-45bd-89ab-a0edd985cfad.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-934fca59-2994-4eb0-8f4f-528b0815bc9a",
    "src": "/images/drawings/drawings-naar-model-934fca59-2994-4eb0-8f4f-528b0815bc9a.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-947fec04-1b25-4093-8695-8da339140865",
    "src": "/images/drawings/drawings-naar-model-947fec04-1b25-4093-8695-8da339140865.jpg",
    "title": "Oil on Board",
    "size": "70 × 55 cm",
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-9dd31020-4393-404e-8910-af46c1d79b36",
    "src": "/images/drawings/drawings-naar-model-9dd31020-4393-404e-8910-af46c1d79b36.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-9e220292-ba39-42c8-b803-97955f817a91",
    "src": "/images/drawings/drawings-naar-model-9e220292-ba39-42c8-b803-97955f817a91.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-ab8ad297-0eca-4595-a454-4bfc45ced9ad",
    "src": "/images/drawings/drawings-naar-model-ab8ad297-0eca-4595-a454-4bfc45ced9ad.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-adba7ac0-5a28-4eba-9166-03fcfe00e942",
    "src": "/images/drawings/drawings-naar-model-adba7ac0-5a28-4eba-9166-03fcfe00e942.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-af26f7f0-418b-4c6d-9483-736a33ff8910",
    "src": "/images/drawings/drawings-naar-model-af26f7f0-418b-4c6d-9483-736a33ff8910.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-b59d40d0-d88f-47df-812a-066ac6ffcb64",
    "src": "/images/drawings/drawings-naar-model-b59d40d0-d88f-47df-812a-066ac6ffcb64.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-b5ac4d95-e011-4306-a404-5a995c720d8f",
    "src": "/images/drawings/drawings-naar-model-b5ac4d95-e011-4306-a404-5a995c720d8f.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-b77c8b1c-85f3-446d-b058-7a14cdd25863",
    "src": "/images/drawings/drawings-naar-model-b77c8b1c-85f3-446d-b058-7a14cdd25863.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-b8c27c64-62c7-4f93-bc95-877afb71f348",
    "src": "/images/drawings/drawings-naar-model-b8c27c64-62c7-4f93-bc95-877afb71f348.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-baa00439-36fb-4693-9b40-568a0f3f65ed",
    "src": "/images/drawings/drawings-naar-model-baa00439-36fb-4693-9b40-568a0f3f65ed.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-bcb88841-0f40-4dd7-8055-a218e765e540",
    "src": "/images/drawings/drawings-naar-model-bcb88841-0f40-4dd7-8055-a218e765e540.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-c20d5841-fd0e-4c8b-b591-ad83a3dfa90c",
    "src": "/images/drawings/drawings-naar-model-c20d5841-fd0e-4c8b-b591-ad83a3dfa90c.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-c340bae0-1cc9-4a69-8ce9-37b90e1d1f6b",
    "src": "/images/drawings/drawings-naar-model-c340bae0-1cc9-4a69-8ce9-37b90e1d1f6b.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-c5f18c35-93c4-43e9-b248-e83ef55a3533",
    "src": "/images/drawings/drawings-naar-model-c5f18c35-93c4-43e9-b248-e83ef55a3533.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-c6ed96b7-2ff5-492e-b71e-3f87492a4a88",
    "src": "/images/drawings/drawings-naar-model-c6ed96b7-2ff5-492e-b71e-3f87492a4a88.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-c7aa1e95-4455-4e6e-b108-7e7c3f1008f4",
    "src": "/images/drawings/drawings-naar-model-c7aa1e95-4455-4e6e-b108-7e7c3f1008f4.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-c7de0d5a-c560-4c74-a6d1-6cfaa1302074",
    "src": "/images/drawings/drawings-naar-model-c7de0d5a-c560-4c74-a6d1-6cfaa1302074.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-c90a5a57-e101-4b98-be48-0104273c2e22",
    "src": "/images/drawings/drawings-naar-model-c90a5a57-e101-4b98-be48-0104273c2e22.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-cae214af-0423-4677-8f47-47ef667059a8",
    "src": "/images/drawings/drawings-naar-model-cae214af-0423-4677-8f47-47ef667059a8.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-cc9c3b26-de29-4b4e-b3f0-0a2d4958c2ae",
    "src": "/images/drawings/drawings-naar-model-cc9c3b26-de29-4b4e-b3f0-0a2d4958c2ae.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-ce8e3d38-e6e5-44b9-91de-d8fda622e1f7",
    "src": "/images/drawings/drawings-naar-model-ce8e3d38-e6e5-44b9-91de-d8fda622e1f7.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-d5a3f8b4-4185-4ee0-bef9-61febee6371b",
    "src": "/images/drawings/drawings-naar-model-d5a3f8b4-4185-4ee0-bef9-61febee6371b.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-d6147df1-0122-453d-8e76-45ef2a022c9f",
    "src": "/images/drawings/drawings-naar-model-d6147df1-0122-453d-8e76-45ef2a022c9f.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-d7bddb19-4506-435b-a97c-42c98e914b00",
    "src": "/images/drawings/drawings-naar-model-d7bddb19-4506-435b-a97c-42c98e914b00.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-d8662524-c6c6-43ff-a10c-e753d52c4485",
    "src": "/images/drawings/drawings-naar-model-d8662524-c6c6-43ff-a10c-e753d52c4485.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-d8b96d87-c947-43d6-ae34-79661f7c1bca",
    "src": "/images/drawings/drawings-naar-model-d8b96d87-c947-43d6-ae34-79661f7c1bca.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-d94e5e80-0429-4462-8ff4-5df3440b7137",
    "src": "/images/drawings/drawings-naar-model-d94e5e80-0429-4462-8ff4-5df3440b7137.jpg",
    "title": "drawings 715 2",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-dac8913a-f8d1-4ab7-846c-87e71adf5df4",
    "src": "/images/drawings/drawings-naar-model-dac8913a-f8d1-4ab7-846c-87e71adf5df4.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-e8b02a97-c4db-42b7-bdaa-7c275c54998e",
    "src": "/images/drawings/drawings-naar-model-e8b02a97-c4db-42b7-bdaa-7c275c54998e.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-eac0bc15-3360-4364-bd4c-cfb02fa3015b",
    "src": "/images/drawings/drawings-naar-model-eac0bc15-3360-4364-bd4c-cfb02fa3015b.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-eb6a4157-72d4-4f4e-912f-f335aab17cc9",
    "src": "/images/drawings/drawings-naar-model-eb6a4157-72d4-4f4e-912f-f335aab17cc9.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-f3a41f50-a9b2-4e60-abf3-e9a30317187d",
    "src": "/images/drawings/drawings-naar-model-f3a41f50-a9b2-4e60-abf3-e9a30317187d.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-f4dfc374-16e7-40c4-a2c6-387ebb1cf364",
    "src": "/images/drawings/drawings-naar-model-f4dfc374-16e7-40c4-a2c6-387ebb1cf364.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-f4e7c0e2-499a-4a59-8bb1-e966418cafdc",
    "src": "/images/drawings/drawings-naar-model-f4e7c0e2-499a-4a59-8bb1-e966418cafdc.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-f774ec01-5aed-4790-9856-1ea9428835fb",
    "src": "/images/drawings/drawings-naar-model-f774ec01-5aed-4790-9856-1ea9428835fb.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-f9aa9787-c9ac-4278-8e18-dbc998c237ae",
    "src": "/images/drawings/drawings-naar-model-f9aa9787-c9ac-4278-8e18-dbc998c237ae.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-faadeaa3-ba82-44f6-a1ba-78a91dfc8ad7",
    "src": "/images/drawings/drawings-naar-model-faadeaa3-ba82-44f6-a1ba-78a91dfc8ad7.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-naar-model-fafb4c44-4ce3-4191-9e49-47659b178cab",
    "src": "/images/drawings/drawings-naar-model-fafb4c44-4ce3-4191-9e49-47659b178cab.jpg",
    "title": "Figure Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-1b9ab275-3849-4d5d-b9e4-dfa82955cf33",
    "src": "/images/drawings/drawings-still-life-interior-1b9ab275-3849-4d5d-b9e4-dfa82955cf33.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-40f7598d-312c-4838-a539-2ed14584f172",
    "src": "/images/drawings/drawings-still-life-interior-40f7598d-312c-4838-a539-2ed14584f172.jpg",
    "title": "copy 2",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-56625726-62af-45ac-b080-31182e2d1a99",
    "src": "/images/drawings/drawings-still-life-interior-56625726-62af-45ac-b080-31182e2d1a99.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-6136ee74-6e1b-49cb-959c-9487f104b8cc",
    "src": "/images/drawings/drawings-still-life-interior-6136ee74-6e1b-49cb-959c-9487f104b8cc.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-780170be-a0ab-4d31-b1ef-016ff2bef493",
    "src": "/images/drawings/drawings-still-life-interior-780170be-a0ab-4d31-b1ef-016ff2bef493.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-7bf42dfc-f72d-40c9-bc4c-661c198f41c0",
    "src": "/images/drawings/drawings-still-life-interior-7bf42dfc-f72d-40c9-bc4c-661c198f41c0.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-94d3cd63-cc36-4107-b1fc-a7ded10c9e07",
    "src": "/images/drawings/drawings-still-life-interior-94d3cd63-cc36-4107-b1fc-a7ded10c9e07.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-9a7035dd-b875-4fea-a9af-f3314497906b",
    "src": "/images/drawings/drawings-still-life-interior-9a7035dd-b875-4fea-a9af-f3314497906b.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-9ea2203b-d139-4794-a3ed-8d9b0609d788",
    "src": "/images/drawings/drawings-still-life-interior-9ea2203b-d139-4794-a3ed-8d9b0609d788.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-a11a608f-1dfd-4acd-a10c-57304f4c7956",
    "src": "/images/drawings/drawings-still-life-interior-a11a608f-1dfd-4acd-a10c-57304f4c7956.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-b0294072-0822-4725-9f0f-2ee98da71bb8",
    "src": "/images/drawings/drawings-still-life-interior-b0294072-0822-4725-9f0f-2ee98da71bb8.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "drawings-still-life-interior-b53622b2-1716-4263-bdb9-7cff9680637f",
    "src": "/images/drawings/drawings-still-life-interior-b53622b2-1716-4263-bdb9-7cff9680637f.jpg",
    "title": "Still Life Drawing",
    "size": null,
    "year": null,
    "category": "drawings",
    "subcategory": "still-life-interior",
    "available": false
  },
  {
    "id": "paintings-featured-jerez-de-la-frontera",
    "src": "/images/paintings/jerez-de-la-frontera.png",
    "title": "Jerez de la Frontera",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "featured",
    "available": false
  },
  {
    "id": "paintings-featured-0cb288d3-4e29-4891-aa94-cd80d75b30d7",
    "src": "/images/paintings/paintings-featured-0cb288d3-4e29-4891-aa94-cd80d75b30d7.jpg",
    "title": "SLAC Exhibition, 2018",
    "size": null,
    "year": 2018,
    "category": "paintings",
    "subcategory": "featured",
    "available": false
  },
  {
    "id": "paintings-naar-model-07e8f990-cac7-41ce-90fa-e9463012269d",
    "src": "/images/paintings/paintings-naar-model-07e8f990-cac7-41ce-90fa-e9463012269d.jpg",
    "title": "Oil on Canvas",
    "size": "70 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-0f37bbbd-975d-4273-a379-91bd1270ac7c",
    "src": "/images/paintings/paintings-naar-model-0f37bbbd-975d-4273-a379-91bd1270ac7c.jpg",
    "title": "80X80",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-10b15c19-fe9a-4594-8a4d-69bbe0c5900d",
    "src": "/images/paintings/paintings-naar-model-10b15c19-fe9a-4594-8a4d-69bbe0c5900d.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-17c551df-c923-42b3-a612-a95c4888d2f5",
    "src": "/images/paintings/paintings-naar-model-17c551df-c923-42b3-a612-a95c4888d2f5.jpg",
    "title": "Oil on Board",
    "size": "55 × 40 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-1d01cca3-f5d5-41f4-af49-7268c2e1fa72",
    "src": "/images/paintings/paintings-naar-model-1d01cca3-f5d5-41f4-af49-7268c2e1fa72.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-218d7b9a-58b0-4921-a0e6-806a90b83ba4",
    "src": "/images/paintings/paintings-naar-model-218d7b9a-58b0-4921-a0e6-806a90b83ba4.jpg",
    "title": "60X60",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-2bdcbf1f-2458-4b93-9299-f2fecd641a5c",
    "src": "/images/paintings/paintings-naar-model-2bdcbf1f-2458-4b93-9299-f2fecd641a5c.jpg",
    "title": "60X60",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-30461520-3c7f-495f-9e40-82e9b0bdf824",
    "src": "/images/paintings/paintings-naar-model-30461520-3c7f-495f-9e40-82e9b0bdf824.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 70 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-322a2712-1c29-4a90-b53f-68e657155c2b",
    "src": "/images/paintings/paintings-naar-model-322a2712-1c29-4a90-b53f-68e657155c2b.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-39db0e32-127e-4d64-af1c-867961d71ded",
    "src": "/images/paintings/paintings-naar-model-39db0e32-127e-4d64-af1c-867961d71ded.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-44402acb-83c9-476e-af5c-d489dffe22e4",
    "src": "/images/paintings/paintings-naar-model-44402acb-83c9-476e-af5c-d489dffe22e4.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-490a7abe-4fe5-4be4-ace1-5d222982cc20",
    "src": "/images/paintings/paintings-naar-model-490a7abe-4fe5-4be4-ace1-5d222982cc20.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-4915dc43-57c1-4c1f-8d7e-bccb3307349c",
    "src": "/images/paintings/paintings-naar-model-4915dc43-57c1-4c1f-8d7e-bccb3307349c.jpg",
    "title": "55X70",
    "size": "55 × 70 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-4a3c955e-13e4-4dfe-922a-31ecc2faf17d",
    "src": "/images/paintings/paintings-naar-model-4a3c955e-13e4-4dfe-922a-31ecc2faf17d.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-5393175c-a478-4c57-9b1e-642cfad957b2",
    "src": "/images/paintings/paintings-naar-model-5393175c-a478-4c57-9b1e-642cfad957b2.jpg",
    "title": "Oil on Canvas",
    "size": "90 × 65 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-53d3fdbd-dcca-434b-ac56-d444d33ed20e",
    "src": "/images/paintings/paintings-naar-model-53d3fdbd-dcca-434b-ac56-d444d33ed20e.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-5e5dfdda-1cf3-4c0f-a856-b058fe0033b3",
    "src": "/images/paintings/paintings-naar-model-5e5dfdda-1cf3-4c0f-a856-b058fe0033b3.jpg",
    "title": "Oil on Canvas",
    "size": "50 × 40 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-601e11e4-b24d-443d-9694-89133e26aa30",
    "src": "/images/paintings/paintings-naar-model-601e11e4-b24d-443d-9694-89133e26aa30.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-6379dedc-e043-4fd4-b702-824d77a94385",
    "src": "/images/paintings/paintings-naar-model-6379dedc-e043-4fd4-b702-824d77a94385.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-638520d8-dfca-496c-b273-0ea6f97dfab2",
    "src": "/images/paintings/paintings-naar-model-638520d8-dfca-496c-b273-0ea6f97dfab2.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-6da6c8e7-6071-4b77-b6fa-516b9f98204d",
    "src": "/images/paintings/paintings-naar-model-6da6c8e7-6071-4b77-b6fa-516b9f98204d.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-6e325115-f497-40e8-9e10-4404470af6c7",
    "src": "/images/paintings/paintings-naar-model-6e325115-f497-40e8-9e10-4404470af6c7.jpg",
    "title": "Oil on Canvas",
    "size": "70 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-6efbb9ea-5cc2-4c13-98f5-ad7a1b45a011",
    "src": "/images/paintings/paintings-naar-model-6efbb9ea-5cc2-4c13-98f5-ad7a1b45a011.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-70aa1d44-d60f-4079-80c8-d8f04be871a3",
    "src": "/images/paintings/paintings-naar-model-70aa1d44-d60f-4079-80c8-d8f04be871a3.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-72a0b463-0ff4-4fd1-8632-8dc500b25433",
    "src": "/images/paintings/paintings-naar-model-72a0b463-0ff4-4fd1-8632-8dc500b25433.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-79cf104c-a2c8-4cdb-ad91-17d802dfbe6f",
    "src": "/images/paintings/paintings-naar-model-79cf104c-a2c8-4cdb-ad91-17d802dfbe6f.jpg",
    "title": "80X80",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-7a1633c4-6af5-4dd5-8b23-841d28dfa97b",
    "src": "/images/paintings/paintings-naar-model-7a1633c4-6af5-4dd5-8b23-841d28dfa97b.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 70 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-7d8697dd-ae05-45df-b3e0-dc5dbfdc92de",
    "src": "/images/paintings/paintings-naar-model-7d8697dd-ae05-45df-b3e0-dc5dbfdc92de.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 70 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-7e7e23fa-257b-4d8c-8fed-4ffaf501511a",
    "src": "/images/paintings/paintings-naar-model-7e7e23fa-257b-4d8c-8fed-4ffaf501511a.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-7f12a60a-a083-4f1b-9c86-bfbaaf0b566c",
    "src": "/images/paintings/paintings-naar-model-7f12a60a-a083-4f1b-9c86-bfbaaf0b566c.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-821859e5-21da-46b3-9fae-ee470f17ba26",
    "src": "/images/paintings/paintings-naar-model-821859e5-21da-46b3-9fae-ee470f17ba26.jpg",
    "title": "Oil on Board",
    "size": "36 × 55 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-865384bd-b32e-4fb4-a160-b7f69af5a229",
    "src": "/images/paintings/paintings-naar-model-865384bd-b32e-4fb4-a160-b7f69af5a229.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-8ac2d475-4cb9-417a-8d71-4509c0690eb5",
    "src": "/images/paintings/paintings-naar-model-8ac2d475-4cb9-417a-8d71-4509c0690eb5.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-9632a6e2-bd5b-4b7f-a702-ee47e630c7db",
    "src": "/images/paintings/paintings-naar-model-9632a6e2-bd5b-4b7f-a702-ee47e630c7db.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-99d683b4-0c20-4156-baf0-2ff21d763e77",
    "src": "/images/paintings/paintings-naar-model-99d683b4-0c20-4156-baf0-2ff21d763e77.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 70 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-b785bc47-4b88-4372-930c-0fe5dd56179e",
    "src": "/images/paintings/paintings-naar-model-b785bc47-4b88-4372-930c-0fe5dd56179e.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-b817f7ec-3811-438f-b9df-4af46e273a7b",
    "src": "/images/paintings/paintings-naar-model-b817f7ec-3811-438f-b9df-4af46e273a7b.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-c202c53a-1811-46e6-a805-42ee9744b71c",
    "src": "/images/paintings/paintings-naar-model-c202c53a-1811-46e6-a805-42ee9744b71c.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-c21c7a5f-3a10-4845-bb8c-88f55329e82a",
    "src": "/images/paintings/paintings-naar-model-c21c7a5f-3a10-4845-bb8c-88f55329e82a.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-c362df49-c32f-474c-a944-7ad5178615bc",
    "src": "/images/paintings/paintings-naar-model-c362df49-c32f-474c-a944-7ad5178615bc.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-c43023e9-19ad-4d08-a148-bcb805f01867",
    "src": "/images/paintings/paintings-naar-model-c43023e9-19ad-4d08-a148-bcb805f01867.jpg",
    "title": "60X80",
    "size": "60 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-ce7cf0cf-61bd-4037-a210-fbeb019cd105",
    "src": "/images/paintings/paintings-naar-model-ce7cf0cf-61bd-4037-a210-fbeb019cd105.jpg",
    "title": "ketch",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-d468095b-1f7e-428d-a95f-13fd76298899",
    "src": "/images/paintings/paintings-naar-model-d468095b-1f7e-428d-a95f-13fd76298899.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-d52abe0b-8f9e-478f-b5ae-3e25020c5166",
    "src": "/images/paintings/paintings-naar-model-d52abe0b-8f9e-478f-b5ae-3e25020c5166.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-d7e1356b-9d19-491c-8cbf-0f7b50194cc9",
    "src": "/images/paintings/paintings-naar-model-d7e1356b-9d19-491c-8cbf-0f7b50194cc9.jpg",
    "title": "Figure Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-deb28c37-de30-4a5e-9d31-1c0c5359ca7d",
    "src": "/images/paintings/paintings-naar-model-deb28c37-de30-4a5e-9d31-1c0c5359ca7d.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-e1ec1788-245b-4fa4-a9c1-03d607f56728",
    "src": "/images/paintings/paintings-naar-model-e1ec1788-245b-4fa4-a9c1-03d607f56728.jpg",
    "title": "80X80",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-eabb3f59-99eb-41aa-b5cd-657429a735d3",
    "src": "/images/paintings/paintings-naar-model-eabb3f59-99eb-41aa-b5cd-657429a735d3.jpg",
    "title": "Oil on Canvas",
    "size": "80 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-f2c51821-28d8-4f1c-b97f-f22fecfa96bd",
    "src": "/images/paintings/paintings-naar-model-f2c51821-28d8-4f1c-b97f-f22fecfa96bd.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 70 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-f55539c8-b788-48e0-ba2c-34d4503c12bf",
    "src": "/images/paintings/paintings-naar-model-f55539c8-b788-48e0-ba2c-34d4503c12bf.jpg",
    "title": "65X90",
    "size": "65 × 90 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-f8dda28f-0688-444c-9ecf-ad1440c2b746",
    "src": "/images/paintings/paintings-naar-model-f8dda28f-0688-444c-9ecf-ad1440c2b746.jpg",
    "title": "Oil on Canvas",
    "size": "70 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-naar-model-fbc4cc61-996a-4c72-8a8b-12befda35230",
    "src": "/images/paintings/paintings-naar-model-fbc4cc61-996a-4c72-8a8b-12befda35230.jpg",
    "title": "Oil on Canvas",
    "size": "50 × 50 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "naar-model",
    "available": false
  },
  {
    "id": "paintings-recent-034836c0-cada-480a-b913-252696fafcb1",
    "src": "/images/paintings/paintings-recent-034836c0-cada-480a-b913-252696fafcb1.jpg",
    "title": "80X60",
    "size": "80 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-0b422981-58a5-4b40-8c86-169da6630f0e",
    "src": "/images/paintings/paintings-recent-0b422981-58a5-4b40-8c86-169da6630f0e.jpg",
    "title": "60x80",
    "size": "60 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-0e30a070-054f-411c-8bfd-81658a4c021a",
    "src": "/images/paintings/paintings-recent-0e30a070-054f-411c-8bfd-81658a4c021a.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-339b1752-11de-4ada-a632-1a82791a90ef",
    "src": "/images/paintings/paintings-recent-339b1752-11de-4ada-a632-1a82791a90ef.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-4ab022fe-576f-4754-b02d-ac7ee99bdacb",
    "src": "/images/paintings/paintings-recent-4ab022fe-576f-4754-b02d-ac7ee99bdacb.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-5d05c061-5763-470d-bddc-67c8576b8125",
    "src": "/images/paintings/paintings-recent-5d05c061-5763-470d-bddc-67c8576b8125.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-63bc4359-ec29-4fea-9a9e-e19156eb9e5f",
    "src": "/images/paintings/paintings-recent-63bc4359-ec29-4fea-9a9e-e19156eb9e5f.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-678317fe-196d-4930-9a6c-d55df63e9923",
    "src": "/images/paintings/paintings-recent-678317fe-196d-4930-9a6c-d55df63e9923.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-8476edf2-e923-41a7-a838-8f09bce0ced6",
    "src": "/images/paintings/paintings-recent-8476edf2-e923-41a7-a838-8f09bce0ced6.jpg",
    "title": "60x80",
    "size": "60 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-a6adbed6-d7ad-4bb5-9f65-87992254e983",
    "src": "/images/paintings/paintings-recent-a6adbed6-d7ad-4bb5-9f65-87992254e983.jpg",
    "title": "Oil on Board",
    "size": "75 × 55 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": true
  },
  {
    "id": "paintings-recent-b76f3608-140b-4981-bf2e-ed44a26d7078",
    "src": "/images/paintings/paintings-recent-b76f3608-140b-4981-bf2e-ed44a26d7078.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-c063eff7-0343-4763-883c-ffab9fd9b598",
    "src": "/images/paintings/paintings-recent-c063eff7-0343-4763-883c-ffab9fd9b598.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-c26109de-d08c-457c-8066-aece802c9a51",
    "src": "/images/paintings/paintings-recent-c26109de-d08c-457c-8066-aece802c9a51.jpg",
    "title": "Oil on Board",
    "size": "65 × 55 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": true
  },
  {
    "id": "paintings-recent-c5904b69-6405-484a-8970-8ffe4ad98a7e",
    "src": "/images/paintings/paintings-recent-c5904b69-6405-484a-8970-8ffe4ad98a7e.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-recent-d75f0389-a605-48df-b76e-8bd36cff97d2",
    "src": "/images/paintings/paintings-recent-d75f0389-a605-48df-b76e-8bd36cff97d2.jpg",
    "title": "Oil Painting",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "recent",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-00eb41dd-915d-47be-a206-adaf5e3dea9d",
    "src": "/images/paintings/paintings-still-life-landscape-00eb41dd-915d-47be-a206-adaf5e3dea9d.jpg",
    "title": "Oil on Board",
    "size": "40 × 55 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-0167702c-6df9-4b4e-a765-2f869599421a",
    "src": "/images/paintings/paintings-still-life-landscape-0167702c-6df9-4b4e-a765-2f869599421a.jpg",
    "title": "Oil on Board",
    "size": "36 × 27 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-03b08c2e-0b75-4371-8180-6d90f7e432e6",
    "src": "/images/paintings/paintings-still-life-landscape-03b08c2e-0b75-4371-8180-6d90f7e432e6.jpg",
    "title": "Oil on Board",
    "size": "55 × 35 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-08f360b4-0608-4eb6-b27b-7cd22e43ab3a",
    "src": "/images/paintings/paintings-still-life-landscape-08f360b4-0608-4eb6-b27b-7cd22e43ab3a.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-1b1c2fe9-22b3-4edb-ac52-20674898ada3",
    "src": "/images/paintings/paintings-still-life-landscape-1b1c2fe9-22b3-4edb-ac52-20674898ada3.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-22d7f44c-2229-4936-ac0d-2278f9b90a2a",
    "src": "/images/paintings/paintings-still-life-landscape-22d7f44c-2229-4936-ac0d-2278f9b90a2a.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 70 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-27baf277-498a-4f1a-8291-656deb95a59e",
    "src": "/images/paintings/paintings-still-life-landscape-27baf277-498a-4f1a-8291-656deb95a59e.jpg",
    "title": "Oil on Board",
    "size": "36 × 27 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-30fc8932-145c-48b7-9736-3335a9d5f87c",
    "src": "/images/paintings/paintings-still-life-landscape-30fc8932-145c-48b7-9736-3335a9d5f87c.jpg",
    "title": "carton",
    "size": "55 × 36 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-31f1b2b8-bee5-43f5-96be-a0a5ab225243",
    "src": "/images/paintings/paintings-still-life-landscape-31f1b2b8-bee5-43f5-96be-a0a5ab225243.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-383a183f-b742-4dfd-86f3-1529dab08178",
    "src": "/images/paintings/paintings-still-life-landscape-383a183f-b742-4dfd-86f3-1529dab08178.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-516d6af7-8f4d-4139-b6a6-3d0a79d1c8f0",
    "src": "/images/paintings/paintings-still-life-landscape-516d6af7-8f4d-4139-b6a6-3d0a79d1c8f0.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-5288c825-3622-4583-8345-0903422817f5",
    "src": "/images/paintings/paintings-still-life-landscape-5288c825-3622-4583-8345-0903422817f5.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-5c92c54b-9d1a-4f5e-b7c5-f285b615b0d1",
    "src": "/images/paintings/paintings-still-life-landscape-5c92c54b-9d1a-4f5e-b7c5-f285b615b0d1.jpg",
    "title": "Oil on Board",
    "size": "65 × 50 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-7fd16535-2a24-4749-9146-23a87eee2f6f",
    "src": "/images/paintings/paintings-still-life-landscape-7fd16535-2a24-4749-9146-23a87eee2f6f.jpg",
    "title": "Oil on Board",
    "size": "65 × 50 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-80ab7842-0e6e-46e7-b5b9-cbfa95227af0",
    "src": "/images/paintings/paintings-still-life-landscape-80ab7842-0e6e-46e7-b5b9-cbfa95227af0.jpg",
    "title": "Oil on Board",
    "size": "65 × 50 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-8d428941-850b-4da0-b0d6-09d2c5e7acde",
    "src": "/images/paintings/paintings-still-life-landscape-8d428941-850b-4da0-b0d6-09d2c5e7acde.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 80 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-8e4f9032-e80c-4d02-8f5e-171a669d9eaf",
    "src": "/images/paintings/paintings-still-life-landscape-8e4f9032-e80c-4d02-8f5e-171a669d9eaf.jpg",
    "title": "Oil on Board",
    "size": "30 × 39 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-9c3678e1-262e-47a0-8073-f7c9e2797c69",
    "src": "/images/paintings/paintings-still-life-landscape-9c3678e1-262e-47a0-8073-f7c9e2797c69.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-9eef3fc7-a910-43c8-bff8-8a1596492b28",
    "src": "/images/paintings/paintings-still-life-landscape-9eef3fc7-a910-43c8-bff8-8a1596492b28.jpg",
    "title": "Oil on Board",
    "size": "65 × 50 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-c1a619cc-ad09-44b5-9abf-3990069012d2",
    "src": "/images/paintings/paintings-still-life-landscape-c1a619cc-ad09-44b5-9abf-3990069012d2.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-c32f79bc-5e20-4e7f-9129-d997d92db3ff",
    "src": "/images/paintings/paintings-still-life-landscape-c32f79bc-5e20-4e7f-9129-d997d92db3ff.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-c61a6101-274f-4aa3-9edf-db95dc51c695",
    "src": "/images/paintings/paintings-still-life-landscape-c61a6101-274f-4aa3-9edf-db95dc51c695.jpg",
    "title": "Still Life",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-c69550f0-9a36-4724-8137-f3e8c75701e9",
    "src": "/images/paintings/paintings-still-life-landscape-c69550f0-9a36-4724-8137-f3e8c75701e9.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-d14a6e6a-833d-4cfc-b29b-57d9b2d902d0",
    "src": "/images/paintings/paintings-still-life-landscape-d14a6e6a-833d-4cfc-b29b-57d9b2d902d0.jpg",
    "title": "Oil on Board",
    "size": "36 × 27 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-dc544693-4e26-4b4c-8247-f8c7f8d0008c",
    "src": "/images/paintings/paintings-still-life-landscape-dc544693-4e26-4b4c-8247-f8c7f8d0008c.jpg",
    "title": "Oil on Board",
    "size": "42 × 41 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-dcccc449-4119-4eb4-a680-66a54cd6ad2f",
    "src": "/images/paintings/paintings-still-life-landscape-dcccc449-4119-4eb4-a680-66a54cd6ad2f.jpg",
    "title": "olie op carton",
    "size": "55 × 73 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-e02459bd-cd98-4f05-8095-bb4db1c6cfcc",
    "src": "/images/paintings/paintings-still-life-landscape-e02459bd-cd98-4f05-8095-bb4db1c6cfcc.jpg",
    "title": "Oil on Board",
    "size": "45 × 64 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-e097ebfd-971d-47ef-b4d8-8044a018e1b6-jpg",
    "src": "/images/paintings/paintings-still-life-landscape-e097ebfd-971d-47ef-b4d8-8044a018e1b6-jpg.jpg",
    "title": "jas",
    "size": null,
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-e592241f-d23c-4043-a454-f3059ba462e6",
    "src": "/images/paintings/paintings-still-life-landscape-e592241f-d23c-4043-a454-f3059ba462e6.jpg",
    "title": "Oil on Board",
    "size": "70 × 55 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-e742ccee-bb1b-455a-8167-e430a08a387c",
    "src": "/images/paintings/paintings-still-life-landscape-e742ccee-bb1b-455a-8167-e430a08a387c.jpg",
    "title": "Oil on Board",
    "size": "50 × 40 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "paintings-still-life-landscape-f971193e-e403-4170-acdd-97e3d8208887",
    "src": "/images/paintings/paintings-still-life-landscape-f971193e-e403-4170-acdd-97e3d8208887.jpg",
    "title": "Oil on Canvas",
    "size": "60 × 60 cm",
    "year": null,
    "category": "paintings",
    "subcategory": "still-life-landscape",
    "available": false
  },
  {
    "id": "portraits-drawings-082a9625-24e4-4463-84a7-d132bdf21ba9",
    "src": "/images/portraits/portraits-drawings-082a9625-24e4-4463-84a7-d132bdf21ba9.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-0d868657-b16c-45e4-acdd-6b4d00520ade",
    "src": "/images/portraits/portraits-drawings-0d868657-b16c-45e4-acdd-6b4d00520ade.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-1a24f523-1b2a-42c9-9cca-69b63907763b",
    "src": "/images/portraits/portraits-drawings-1a24f523-1b2a-42c9-9cca-69b63907763b.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-1a5c713f-9e21-4381-b4c2-286de0a1de6d",
    "src": "/images/portraits/portraits-drawings-1a5c713f-9e21-4381-b4c2-286de0a1de6d.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-1ac36796-3694-472f-b25d-f7d66af5b47f",
    "src": "/images/portraits/portraits-drawings-1ac36796-3694-472f-b25d-f7d66af5b47f.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-200c202e-45e2-4589-9240-9d7bd014a73e",
    "src": "/images/portraits/portraits-drawings-200c202e-45e2-4589-9240-9d7bd014a73e.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-20e5afde-fbf5-4fd2-9774-16ce122054da",
    "src": "/images/portraits/portraits-drawings-20e5afde-fbf5-4fd2-9774-16ce122054da.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-2ca697f9-2cd4-46aa-9c09-7c6c8f275314",
    "src": "/images/portraits/portraits-drawings-2ca697f9-2cd4-46aa-9c09-7c6c8f275314.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-2eed40d6-a994-4542-aaff-4a9cb60f858b",
    "src": "/images/portraits/portraits-drawings-2eed40d6-a994-4542-aaff-4a9cb60f858b.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-2f353755-addd-48b3-81a4-012f17a14253",
    "src": "/images/portraits/portraits-drawings-2f353755-addd-48b3-81a4-012f17a14253.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-30e4b67d-f548-4581-9510-fc61e0880a7e",
    "src": "/images/portraits/portraits-drawings-30e4b67d-f548-4581-9510-fc61e0880a7e.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-3a9e8f7c-b24c-46c0-9993-5997721225d3",
    "src": "/images/portraits/portraits-drawings-3a9e8f7c-b24c-46c0-9993-5997721225d3.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-472852bb-db45-4ed1-b7c7-518bc3628a10",
    "src": "/images/portraits/portraits-drawings-472852bb-db45-4ed1-b7c7-518bc3628a10.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-4ba807a1-0c74-46c0-b0f2-4b1d097e272f",
    "src": "/images/portraits/portraits-drawings-4ba807a1-0c74-46c0-b0f2-4b1d097e272f.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-54a21bea-6d6b-4cfe-bf03-f57caa8eab65",
    "src": "/images/portraits/portraits-drawings-54a21bea-6d6b-4cfe-bf03-f57caa8eab65.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-638a7f2e-cc8a-40bc-a342-3ab79e34f538",
    "src": "/images/portraits/portraits-drawings-638a7f2e-cc8a-40bc-a342-3ab79e34f538.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-6bc49d9e-6bf3-40bf-9a9d-5e7e751aef26",
    "src": "/images/portraits/portraits-drawings-6bc49d9e-6bf3-40bf-9a9d-5e7e751aef26.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-6bdd1f59-a8df-416d-afc0-a595db4caa10",
    "src": "/images/portraits/portraits-drawings-6bdd1f59-a8df-416d-afc0-a595db4caa10.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-6c000e96-de8c-4e0f-b5f6-6f5a3f321333",
    "src": "/images/portraits/portraits-drawings-6c000e96-de8c-4e0f-b5f6-6f5a3f321333.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-6f5b6914-d30d-43cb-a1db-838d3b61cc17",
    "src": "/images/portraits/portraits-drawings-6f5b6914-d30d-43cb-a1db-838d3b61cc17.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-74ea42f6-c6a7-461d-bcde-3bb4d1b82a61",
    "src": "/images/portraits/portraits-drawings-74ea42f6-c6a7-461d-bcde-3bb4d1b82a61.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-81159ad3-6156-47aa-8fb2-fc419aac83cf",
    "src": "/images/portraits/portraits-drawings-81159ad3-6156-47aa-8fb2-fc419aac83cf.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-8174e525-c3cb-4970-87a4-a37f09d37080",
    "src": "/images/portraits/portraits-drawings-8174e525-c3cb-4970-87a4-a37f09d37080.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-86f24774-8971-4e55-9b3b-e97e01c7580a",
    "src": "/images/portraits/portraits-drawings-86f24774-8971-4e55-9b3b-e97e01c7580a.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-8f70e145-1731-420c-a055-85533f715d34",
    "src": "/images/portraits/portraits-drawings-8f70e145-1731-420c-a055-85533f715d34.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-91f782f1-c2f9-44ea-8c1d-882d4ba31ede",
    "src": "/images/portraits/portraits-drawings-91f782f1-c2f9-44ea-8c1d-882d4ba31ede.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-9cea0e2e-2a44-4bda-8fad-68ece7b4b48f",
    "src": "/images/portraits/portraits-drawings-9cea0e2e-2a44-4bda-8fad-68ece7b4b48f.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-a1ff6a04-1526-428b-9f90-b02bf212bb36",
    "src": "/images/portraits/portraits-drawings-a1ff6a04-1526-428b-9f90-b02bf212bb36.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-bda9020f-9f2e-40cc-b47a-b212567fadbc",
    "src": "/images/portraits/portraits-drawings-bda9020f-9f2e-40cc-b47a-b212567fadbc.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-c0a3e2a9-c9be-4fa5-b952-a37da4fcb9f9",
    "src": "/images/portraits/portraits-drawings-c0a3e2a9-c9be-4fa5-b952-a37da4fcb9f9.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-c1c2e281-70e3-4a5e-a281-2859fd77c8fd",
    "src": "/images/portraits/portraits-drawings-c1c2e281-70e3-4a5e-a281-2859fd77c8fd.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-c7366d29-f2ab-4cab-8201-f20d1a55a0dd",
    "src": "/images/portraits/portraits-drawings-c7366d29-f2ab-4cab-8201-f20d1a55a0dd.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-c8b715d0-4a04-4ad4-87df-e6e02748bb8f",
    "src": "/images/portraits/portraits-drawings-c8b715d0-4a04-4ad4-87df-e6e02748bb8f.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-d08269cf-c785-4ebd-8027-3f67411afa0c",
    "src": "/images/portraits/portraits-drawings-d08269cf-c785-4ebd-8027-3f67411afa0c.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-d5cd0c9b-0501-4ff3-a886-48013532b88f",
    "src": "/images/portraits/portraits-drawings-d5cd0c9b-0501-4ff3-a886-48013532b88f.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-e2cac74a-34d1-42d6-b243-259e32a72d89",
    "src": "/images/portraits/portraits-drawings-e2cac74a-34d1-42d6-b243-259e32a72d89.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-e4f08c59-0737-4984-b0a0-a2b88e5c643d",
    "src": "/images/portraits/portraits-drawings-e4f08c59-0737-4984-b0a0-a2b88e5c643d.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-ec143763-c9fb-4fa3-80a7-954234524729",
    "src": "/images/portraits/portraits-drawings-ec143763-c9fb-4fa3-80a7-954234524729.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-ee1d91a0-f63a-4b39-a8a3-7a172abf9932",
    "src": "/images/portraits/portraits-drawings-ee1d91a0-f63a-4b39-a8a3-7a172abf9932.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-ee8de69d-f0b7-4262-be0f-2704c6f40744",
    "src": "/images/portraits/portraits-drawings-ee8de69d-f0b7-4262-be0f-2704c6f40744.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-f2881fff-2b00-450e-94d6-3b3e6d7d38f8",
    "src": "/images/portraits/portraits-drawings-f2881fff-2b00-450e-94d6-3b3e6d7d38f8.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-f79deedf-d3c5-451f-852e-a96a0604c01e",
    "src": "/images/portraits/portraits-drawings-f79deedf-d3c5-451f-852e-a96a0604c01e.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-drawings-f9bc3ff5-5f26-40b8-a49f-b5c4ee2c1414",
    "src": "/images/portraits/portraits-drawings-f9bc3ff5-5f26-40b8-a49f-b5c4ee2c1414.jpg",
    "title": "Portrait Drawing",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "drawings",
    "available": false
  },
  {
    "id": "portraits-paintings-03146533-b50f-4100-b2bf-033c863963ad",
    "src": "/images/portraits/portraits-paintings-03146533-b50f-4100-b2bf-033c863963ad.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-0d96bdb7-e95b-4d6e-a444-831bc29dd661",
    "src": "/images/portraits/portraits-paintings-0d96bdb7-e95b-4d6e-a444-831bc29dd661.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-1dc2530c-fa10-40fb-b69e-33a0afd016bd",
    "src": "/images/portraits/portraits-paintings-1dc2530c-fa10-40fb-b69e-33a0afd016bd.jpeg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-1f2f4c3b-7276-4fa3-9003-3fe9f0ed260b",
    "src": "/images/portraits/portraits-paintings-1f2f4c3b-7276-4fa3-9003-3fe9f0ed260b.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-41a710e8-286e-4486-affa-e4719017714a",
    "src": "/images/portraits/portraits-paintings-41a710e8-286e-4486-affa-e4719017714a.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-46f3bc10-40d9-45a8-95dd-af1d7fa674cf",
    "src": "/images/portraits/portraits-paintings-46f3bc10-40d9-45a8-95dd-af1d7fa674cf.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-4a7cc12f-c281-400b-9f26-72648ff53fff",
    "src": "/images/portraits/portraits-paintings-4a7cc12f-c281-400b-9f26-72648ff53fff.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-6584e2aa-a4f4-493d-9ade-acbc43b60354",
    "src": "/images/portraits/portraits-paintings-6584e2aa-a4f4-493d-9ade-acbc43b60354.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-703936b4-b9c0-4390-97e4-1174854ae60a",
    "src": "/images/portraits/portraits-paintings-703936b4-b9c0-4390-97e4-1174854ae60a.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-70d92ea9-9599-410e-8d3f-d8bb4babdc71",
    "src": "/images/portraits/portraits-paintings-70d92ea9-9599-410e-8d3f-d8bb4babdc71.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-aea97f39-8fb9-4184-8586-a04616d0ec90",
    "src": "/images/portraits/portraits-paintings-aea97f39-8fb9-4184-8586-a04616d0ec90.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-b08f6e82-48e7-4e77-8301-17253f96017b",
    "src": "/images/portraits/portraits-paintings-b08f6e82-48e7-4e77-8301-17253f96017b.jpeg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-b40776f8-7ce2-49af-a531-b54b58c06da0",
    "src": "/images/portraits/portraits-paintings-b40776f8-7ce2-49af-a531-b54b58c06da0.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-b9e3ffee-9a36-46d0-b383-433d8cd88f0d",
    "src": "/images/portraits/portraits-paintings-b9e3ffee-9a36-46d0-b383-433d8cd88f0d.jpg",
    "title": "50X50",
    "size": "50 × 50 cm",
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-c3973bca-69ea-478f-bea2-99a31b2e60d5",
    "src": "/images/portraits/portraits-paintings-c3973bca-69ea-478f-bea2-99a31b2e60d5.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-ce54675f-7d7c-4fd4-a212-605155031326",
    "src": "/images/portraits/portraits-paintings-ce54675f-7d7c-4fd4-a212-605155031326.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-ef125cc4-22c0-4eb1-8b50-cd6f7beb6dc6",
    "src": "/images/portraits/portraits-paintings-ef125cc4-22c0-4eb1-8b50-cd6f7beb6dc6.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-f5755788-3537-420b-b9fb-b39aa3902531",
    "src": "/images/portraits/portraits-paintings-f5755788-3537-420b-b9fb-b39aa3902531.jpg",
    "title": "Oil on Canvas",
    "size": "50 × 50 cm",
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  },
  {
    "id": "portraits-paintings-fa8d572a-ef08-4cf7-b035-f43ed939c723",
    "src": "/images/portraits/portraits-paintings-fa8d572a-ef08-4cf7-b035-f43ed939c723.jpg",
    "title": "Portrait Painting",
    "size": null,
    "year": null,
    "category": "portraits",
    "subcategory": "paintings",
    "available": false
  }
];

export const heroArtworkId = "paintings-featured-jerez-de-la-frontera";

export function getArtworksByCategory(category: ArtworkCategory): Artwork[] {
  return artworks.filter((a) => a.category === category);
}

export function getAvailableArtworks(): Artwork[] {
  return artworks.filter((a) => a.available);
}

export function getArtworkById(id: string): Artwork | undefined {
  return artworks.find((a) => a.id === id);
}

export function getRecentArtworks(limit = 9): Artwork[] {
  const recent = artworks.filter(
    (a) => a.category === "paintings" && a.subcategory === "recent",
  );
  return (recent.length ? recent : artworks.filter((a) => a.category === "paintings")).slice(
    0,
    limit,
  );
}
