/**
 * Pre-generates WebP variants for static export (replaces next/image optimization).
 *
 * Source:  public/images/ (recursive)
 * Output:  public/images-optimized/ with .w{width}.webp files
 * Manifest: data/image-variants.ts
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const IMAGES_DIR = path.join(ROOT, "public", "images");
const OUTPUT_DIR = path.join(ROOT, "public", "images-optimized");
const MANIFEST_PATH = path.join(ROOT, "data", "image-variants.ts");

const WIDTHS = [400, 800, 1600];
const WEBP_QUALITY = 82;
const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg"]);

function walkImages(dir, files = []) {
  if (!fs.existsSync(dir)) {
    return files;
  }

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkImages(fullPath, files);
      continue;
    }

    const ext = path.extname(entry.name).toLowerCase();
    if (IMAGE_EXTENSIONS.has(ext)) {
      files.push(fullPath);
    }
  }

  return files;
}

function toPublicSrc(filePath) {
  const relative = path.relative(path.join(ROOT, "public"), filePath);
  return `/${relative.split(path.sep).join("/")}`;
}

function variantPath(sourcePath, width) {
  const relative = path.relative(IMAGES_DIR, sourcePath);
  const parsed = path.parse(relative);
  const outputRelative = path.join(
    parsed.dir,
    `${parsed.name}.w${width}.webp`,
  );
  return path.join(OUTPUT_DIR, outputRelative);
}

function variantPublicSrc(sourcePath, width) {
  const relative = path.relative(IMAGES_DIR, sourcePath);
  const parsed = path.parse(relative);
  const outputRelative = path.posix.join(
    parsed.dir.split(path.sep).join("/"),
    `${parsed.name}.w${width}.webp`,
  );
  return `/images-optimized/${outputRelative}`;
}

function isStale(sourcePath, outputPath) {
  if (!fs.existsSync(outputPath)) {
    return true;
  }

  return fs.statSync(outputPath).mtimeMs < fs.statSync(sourcePath).mtimeMs;
}

async function ensureVariant(sourcePath, width) {
  const outputPath = variantPath(sourcePath, width);
  let regenerated = false;

  if (isStale(sourcePath, outputPath)) {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    await sharp(sourcePath)
      .rotate()
      .resize(width, null, {
        fit: "inside",
        withoutEnlargement: true,
      })
      .webp({ quality: WEBP_QUALITY, effort: 4 })
      .toFile(outputPath);
    regenerated = true;
  }

  const meta = await sharp(outputPath).metadata();
  return {
    url: variantPublicSrc(sourcePath, width),
    width: meta.width ?? width,
    regenerated,
  };
}

function writeManifest(manifest) {
  const lines = [
    "/** Auto-generated by scripts/optimize-images.mjs — do not edit manually. */",
    "export type ImageVariantEntry = {",
    "  fallback: string;",
    "  srcSet: string;",
    "};",
    "",
    "export const IMAGE_VARIANTS: Record<string, ImageVariantEntry> = {",
  ];

  const entries = Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b));
  for (const [src, entry] of entries) {
    lines.push(`  ${JSON.stringify(src)}: {`);
    lines.push(`    fallback: ${JSON.stringify(entry.fallback)},`);
    lines.push(`    srcSet: ${JSON.stringify(entry.srcSet)},`);
    lines.push("  },");
  }

  lines.push("};", "");
  fs.writeFileSync(MANIFEST_PATH, lines.join("\n"), "utf8");
}

async function main() {
  const sources = walkImages(IMAGES_DIR);
  const manifest = {};
  let created = 0;
  let cached = 0;

  for (const sourcePath of sources) {
    const parts = [];

    for (const width of WIDTHS) {
      const variant = await ensureVariant(sourcePath, width);
      parts.push({ width: variant.width, url: variant.url });
      if (variant.regenerated) {
        created += 1;
      } else {
        cached += 1;
      }
    }

    const uniqueParts = [...parts]
      .sort((a, b) => a.width - b.width)
      .filter(
        (part, index, array) =>
          index === 0 || part.width !== array[index - 1].width,
      );

    if (uniqueParts.length === 0) {
      continue;
    }

    const fallback =
      uniqueParts.find((part) => part.width >= 800)?.url ??
      uniqueParts[uniqueParts.length - 1].url;

    manifest[toPublicSrc(sourcePath)] = {
      fallback,
      srcSet: uniqueParts.map((part) => `${part.url} ${part.width}w`).join(", "),
    };
  }

  writeManifest(manifest);
  console.log(
    `Optimized ${sources.length} images (${created} variants written, ${cached} cached) → public/images-optimized/`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
